prefix = "./corpora"
stop-words = "./corpora/stopwords.txt"

dataset = "cs-410"
corpus = "cs-410-file.toml"
index = "./corpora/cs-410/idx"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"
