type = "file-corpus"
list = "lectures"

store-full-text = true

metadata = [{name = "video_id", type = "string"},
            {name = "title", type = "string"},
            {name = "AWS_file", type = "string"}]
